REPORT zmc_uebung_11.

" In diesem Beispiel haben wir eine Z-Tabelle, die zmc_perab heißt.
" Wir können erst unsere Tabelle im Layout sehen. Dann können wir
" zwischen gt_table_1 und gt_table_2 die Zeilen wechseln. Am Ende
" gibt es auch eine Möglichkeit die Z-Tabelle zu aktualisieren.

INCLUDE ZMC_UEBUNG_11_TOP.
INCLUDE ZMC_UEBUNG_11_FRM.
INCLUDE ZMC_UEBUNG_11_PBO.
INCLUDE ZMC_UEBUNG_11_PAI.

START-OF-SELECTION.

  PERFORM get_data.

  call SCREEN 0100.

*&SPWIZARD: DECLARATION OF TABLECONTROL 'TABKON' ITSELF
CONTROLS: TABKON TYPE TABLEVIEW USING SCREEN 0100.

*&SPWIZARD: OUTPUT MODULE FOR TC 'TABKON'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: UPDATE LINES FOR EQUIVALENT SCROLLBAR
MODULE TABKON_CHANGE_TC_ATTR OUTPUT.
  DESCRIBE TABLE GT_TABLE_1 LINES TABKON-lines.
ENDMODULE.

*&SPWIZARD: INPUT MODULE FOR TC 'TABKON'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: MODIFY TABLE
MODULE TABKON_MODIFY INPUT.
  MODIFY GT_TABLE_1
    FROM GS_TABLE_1
    INDEX TABKON-CURRENT_LINE.
ENDMODULE.

*&SPWIZARD: INPUT MODUL FOR TC 'TABKON'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: MARK TABLE
MODULE TABKON_MARK INPUT.
  DATA: g_TABKON_wa2 like line of GT_TABLE_1.
    if TABKON-line_sel_mode = 1
    and GS_TABLE_1-SELEKTIEREN = 'X'.
     loop at GT_TABLE_1 into g_TABKON_wa2
       where SELEKTIEREN = 'X'.
       g_TABKON_wa2-SELEKTIEREN = ''.
       modify GT_TABLE_1
         from g_TABKON_wa2
         transporting SELEKTIEREN.
     endloop.
  endif.
  MODIFY GT_TABLE_1
    FROM GS_TABLE_1
    INDEX TABKON-CURRENT_LINE
    TRANSPORTING SELEKTIEREN.
ENDMODULE.

*&SPWIZARD: DECLARATION OF TABLECONTROL 'TABKON2' ITSELF
CONTROLS: TABKON2 TYPE TABLEVIEW USING SCREEN 0100.

*&SPWIZARD: OUTPUT MODULE FOR TC 'TABKON2'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: UPDATE LINES FOR EQUIVALENT SCROLLBAR
MODULE TABKON2_CHANGE_TC_ATTR OUTPUT.
  DESCRIBE TABLE GT_TABLE_2 LINES TABKON2-lines.
ENDMODULE.

*&SPWIZARD: INPUT MODULE FOR TC 'TABKON2'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: MODIFY TABLE
MODULE TABKON2_MODIFY INPUT.
  MODIFY GT_TABLE_2
    FROM GS_TABLE_2
    INDEX TABKON2-CURRENT_LINE.
ENDMODULE.

*&SPWIZARD: INPUT MODUL FOR TC 'TABKON2'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: MARK TABLE
MODULE TABKON2_MARK INPUT.
  DATA: g_TABKON2_wa2 like line of GT_TABLE_2.
    if TABKON2-line_sel_mode = 1
    and GS_TABLE_2-SELEKTIEREN = 'X'.
     loop at GT_TABLE_2 into g_TABKON2_wa2
       where SELEKTIEREN = 'X'.
       g_TABKON2_wa2-SELEKTIEREN = ''.
       modify GT_TABLE_2
         from g_TABKON2_wa2
         transporting SELEKTIEREN.
     endloop.
  endif.
  MODIFY GT_TABLE_2
    FROM GS_TABLE_2
    INDEX TABKON2-CURRENT_LINE
    TRANSPORTING SELEKTIEREN.
ENDMODULE.
