REPORT zmc_uebung_8.

"Container ALV (Auch ein Beispiel von FM Number_Get_Next )

INCLUDE ZMC_UEBUNG_8_TOP.
INCLUDE ZMC_UEBUNG_8_FRM.
INCLUDE ZMC_UEBUNG_8_PBO.
INCLUDE ZMC_UEBUNG_8_PAI.


INITIALIZATION.

  CALL SCREEN 0100.
